FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY . /app/quarkus

RUN cd /app/quarkus \
    && ./mvnw clean package

EXPOSE 8080

ENTRYPOINT ["java","-jar", "/app/quarkus/target/quarkus-app/quarkus-run.jar"]