FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY pom.xml mvnw ./
COPY .mvn .mvn
COPY src src

RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw clean package \
    && cp target/*-spring-boot.jar /app/app.jar \
    && rm -rf src target .mvn mvnw pom.xml

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]