FROM bellsoft/hardened-liberica-runtime-container:jdk-25-musl as builder
WORKDIR /app COPY . /app/spring
RUN cd /app/spring \
    && ./mvnw clean package \
    && cp target/*-spring-boot.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]