FROM eclipse-temurin:25-jdk
WORKDIR /app COPY . /app/spring
RUN cd /app/spring \
    && ./mvnw clean package \
    && cp target/*-spring-boot.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]